#+TITLE: Environment

* Table of Contents :TOC@4:
- [[#summary][Summary]]
- [[#shell-setup-fish][Shell Setup (Fish)]]
  - [[#1-install-fisher][1. Install Fisher]]
  - [[#2-install-plugins][2. Install plugins]]
    - [[#z][z]]
    - [[#fishtape][fishtape]]
    - [[#bass][bass]]
  - [[#3-initializing-and-binding-guix-profile][3. Initializing and binding Guix profile]]
  - [[#4-bind-nix-profile-and-add-channel][4. Bind Nix profile and add channel]]
- [[#emacs][Emacs]]

* Summary

#+BEGIN_QUOTE
The system defined in System.org *must be installed* for any of the below configurations to work.
#+END_QUOTE

After my system installation, but before setting up my desktop environment, I need to set up my shell environment. This means ensuring that my shell is set up correctly, my =PATH= references the correct locations, and all the needed
environment variables are defined.

My environment also includes my editor of choice: GNU Emacs. [[https://github.com/cr-jr/C4][I maintain a separate repo]] for that configuration.

* Shell Setup (Fish)

My shell of choice is Fish. The main thing I do is grab some extra plugins for functionality and a useful prompt. And the easiest way to manage them is [[https://github.com/jorgebucaran/fisher][fisher]].

** 1. Install Fisher

#+BEGIN_SRC shell
curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
#+END_SRC

** 2. Install plugins

*** z

[[https://github.com/jethrokuan/z][z]] fish is a port of a [[https://github.com/rupa/z][ZShell plugin of the same name]]. It allows me to quickly jump to any directory I've visited recently through fuzzy searching.

#+BEGIN_SRC shell
fisher install jethrokuan/z
#+END_SRC

*** fishtape

[[https://github.com/jorgebucaran/fishtape][Fishtape]] is a test runner for fish shell. I mainly use it to help me test scripts and ensure that my environment is behaving as it should.

#+BEGIN_SRC shell
fisher install jorgebucaran/fishtape
#+END_SRC

*** bass

[[https://github.com/edc/bass][Bass]] is a POSIX shell compatibility layer for fish. It allows me to use Bash utilities in fish shell without having to port the script. This plugin streamlines necessary environment configurations and variable assignments that otherwise
expect Bash to be the primary shell.

#+BEGIN_SRC shell
fisher install edc/bass
#+END_SRC

** 3. Initializing and binding Guix profile

#+BEGIN_SRC shell
# Needed to initialize guix profile
guix install hello; guix remove hello

set -x GUIX_PROFILE "$HOME/.guix-profile"
bass source $GUIX_PROFILE/etc/profile
#+END_SRC

** 4. Bind Nix profile and add channel

And then bind my user Nix profile so I can install and manage packages that Guix doesn't provide.

#+BEGIN_SRC shell
bass source /run/current-system/profile/etc/profile.d/nix.sh
nix-channel --add https://nixos.org/channels/nixos-21.05 nixpkgs
nix-channel --update
#+END_SRC

* Emacs

Finally, I set up my Emacs configuration.

#+BEGIN_SRC shell
set -x EMACS_CONFIG "$HOME/.config/emacs"
mkdir -p $EMACS_CONFIG
git clone https://github.com/cr-jr/C4.git $EMACS_CONFIG
emacs --script $EMACS_CONFIG/init.el
#+END_SRC
