#+TITLE: freikugel

* Summary

This repository contains configuration files for my daily work machine. My system uses GNU Guix with
dotfiles managed by GNU Stow. It's always up to date and synced with the host machine.

* Modules

+ System.org: defines the system foundation and packages needed to get it running
+ Env.org: defines the configuration and packages needed to replicate my shell environment
+ Desktop.org: defines the configuration and packages needed replicate my desktop environment
+ Apps.org: defines configuration for my daily programs (Emacs, MPV, etc...)

* Goals

** Primary

+ Self-referential: it should reflect the actual state of the live machine and vice-versa
+ Reproducible: it should be possible to replicate the entire system on a fresh machine
+ Automated: system setup should be scriptable and require very little human effort
+ Portable: in the event of hardware failure, the system should be usable on other machines

** Secondary

+ Composable: modules should be independent yet "talk" to each other
+ PEBKAC-resistant: it should be easily recoverable if I bork something on the live machine
+ Adaptive: it should be painless to change and create system modules
+ Personal: this is /my/ system, after all

* Fork at Your Own Risk

Be aware that this repo deliberately has no license. It's nowhere near the state I'd feel
comfortable with you taking it for a spin on your own machine or using it as a base for your own
system configuration.

For one, it's poorly documented and won't help anyone unfamilar with the tools I'm using. It's also
missing some vital steps in the system setup. The repo is public at this stage solely for quick access.

I'll remove this section and add a license if it's ever stable and secure enough for other people.
