add_newline = false

[line_break]
disabled = true

[username]
show_always = true
format = '[$user]($style)@'

[hostname]
ssh_only = false
format = '[$hostname]($style)'

[git_metrics]
disabled = false
